### ISSUE TITLE
Я  выполнил задание 

### ISSUE THREAD

**Issue by AndreyNikolskiy** [MIEE-ACS/domashnee-zadanie-no3-AndreyNikolskiy#1]
Мой вариант №12. 
Проверьте, пожалуйста

**Comment by AndreyNikolskiy** [comment]
Уточнение : вариант №2 (номер в списке 12)

**Comment by d-makarenko** [comment]
Возможно выпадание двух одинаковых вариантов ответов
Неопрятный внешний вид окна и кода.
3 / 4
